apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo-server
        version: v1
    spec:
      containers:
      - image: ealen/echo-server
        imagePullPolicy: Always
        name: echo
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30